env:
  - TEST_ENV=default
  - TEST_ENV=rails-2.3
  - TEST_ENV=rails-3.0
  - TEST_ENV=rails-3.1
  - TEST_ENV=rails-3.2
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
  - ree
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
    - rvm: ruby-head
  exclude:
    - rvm: ruby-head
      env: TEST_ENV=rails-2.3
notifications:
  email:
    - sysadmin@cramerdev.com

