env:
  - RAILS_VERSION=none capistrano=2.15.5
  - RAILS_VERSION=3.2 capistrano=2.15.5
  - RAILS_VERSION=4.0 capistrano=2.15.5
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email:
    - sysadmin@cramerdev.com

