env:
  - RAILS_VERSION=none
  - RAILS_VERSION=2.3
  - RAILS_VERSION=3.0
  - RAILS_VERSION=3.1
  - RAILS_VERSION=3.2
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
  - ree
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
    - rvm: ruby-head
  exclude:
    - rvm: ruby-head
      env: RAILS_VERSION=2.3
notifications:
  email:
    - sysadmin@cramerdev.com

